### ISSUE TITLE
how to implement on Human3.6m dataset

### ISSUE THREAD

**Issue by gravitychen** [xjwxjw/Pytorch-Robust-Motion-In-betweening#1]
Very nice work! your coding skill is amazing.

I have a question:
LanFan.py  read BVH files to input your pretrain model,
but human3.6 seems to have a different data type, How can I transfer this model to fit Human3.6  or how can I transfer Human3.6 to fit this model

**Comment by xjwxjw** [comment]
I have not tried this and unfortunately, no further plan on this part. After a quick search, I found [this repo](https://github.com/KevinLTT/video2bvh), it seems that [this file](https://github.com/KevinLTT/video2bvh/blob/master/bvh_skeleton/h36m_skeleton.py) provides a solution for converting Human3.6M data into BVH file, which can be processed the same as LaFan. Hope this can help you:).

**Comment by gravitychen** [comment]
Oh~ thank you very much for your quick response and your help!
