### ISSUE TITLE
No module named 'probe'

### ISSUE THREAD

**Issue by Yuefengxin** [xjwxjw/Pytorch-Robust-Motion-In-betweening#2]
Great work! 
I run the code but got the error `No module named 'probe'`. Is there any module missing? Looking forward to your reply!

**Comment by Yuefengxin** [comment]
Oh I just find that in the `deep-motion-editing-baseline` repo. Thanks!

**Comment by JanoschPinsel** [comment]
Hey @Yuefengxin,

I'm stuck with the same problem but couln't find the deep-motion-editing-baseline repo anywhere. Could you provide me with a link? That would help me a lot.

Thank you very much!

**Comment by Yuefengxin** [comment]
You are welcome. This is the link.&nbsp;https://github.com/soomean/deep-motion-editing-baseline




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xjwxjw/Pytorch-Robust-Motion-In-betweening"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月19日(星期五) 晚上8:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xjwxjw/Pytorch-Robust-Motion-In-betweening] No module named 'probe' (#2)





 
Hey @Yuefengxin,
 
I'm stuck with the same problem but couln't find the deep-motion-editing-baseline repo anywhere. Could you provide me with a link? That would help me a lot.
 
Thank you very much!

**Comment by sycamore27** [comment]
Sorry to bether you. I meet the same question, but the link is already not availiable. Could you please share the document or another link? Thank you!!!

**Comment by sycamore27** [comment]
Thanks, I have found the new version link: https://github.com/DeepMotionEditing/deep-motion-editing
