### ISSUE TITLE
Various motions

### ISSUE THREAD

**Issue by vivanov879** [xjwxjw/Pytorch-Robust-Motion-In-betweening#3]
Hey @xjwxjw , this is an interesting project. How do you think the variety of motions can be treated? For example, why would a model connect 2 poses by a dancing sequence, if it can connect them by a walking sequence? I image that 
- the 2 poses need to be close to each other, e.g. 50 frames close, and 
- the 2 poses must be clearly identifiable as dance poses, e.g. poses uncharacteristic to simple walking
- or the training dataset should be restricted to dancing only

maybe there are some other ways to pass a style context to the network? I didn't find any in the paper though. 

As the authors state in their Limitations and Future Work Section, they don't have full control over the style:
```Our scheduled target noise allows us to modify to some extent the manner in which a character reaches its target, reminiscentof changing the style of the motion, but doesn’t allow yet to have control over those variations. Style control given a fixed context would be very interesting but is out of scope of this work.```

**Comment by xjwxjw** [comment]
Interesting topic :) I have not looked deeply into this part. Regarding the diversity of the synthesized motion, maybe [this paper](https://arxiv.org/pdf/2005.08891.pdf) could give you a hint:)

**Comment by vivanov879** [comment]
Alright, thanks for the link =D
