### ISSUE TITLE
Implementation of `lambda_target` function

### ISSUE THREAD

**Issue by ZC119** [xjwxjw/Pytorch-Robust-Motion-In-betweening#4]
Hi!
The implementation of `lambda_target` function in `train.py` and `test.py` seems not right. 

```python
if t < 5:
    lambda_target = 0.0
elif t >=5 and t < 30:
    lambda_target = (t - 5) / 25.0
else:
    lambda_target = 1.0
```

Here parameter `t` seems to be `seq_length - tta` rather than `tta`.

**Comment by ZC119** [comment]
And `ztta[:, t, d-1]` should be `ztta[:, t, d]`
```python
if d % 2 == 0:
    ztta[:, t, d] = np.sin(1.0 * (length - t) / 10000 ** (d / dim))
else:
    ztta[:, t, d] = np.cos(1.0 * (length - t) / 10000 ** (d / dim))
```

**Comment by xjwxjw** [comment]
Deeply thanks for your careful check! I think you are right. Corrected.
